# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
version: 2

issues:
  exclude-files:
    - ".*\\.hcl2spec\\.go$"
  exclude-rules:
    - linters:
        - gosimple
      text: "S(1002|1008|1021)"
    - linters:
        - staticcheck
      text: "SA(1006|1019|4006|4010|4017|5007|6005|9004):"
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - errcheck
      path: ".*_test.go"

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
  fast: true

run:
  concurrency: 4
  timeout: 10m
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - "fmt:.*"
      - "io/ioutil:^Read.*"
      - "io:Close"
