// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package proxmoxlxc

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`

	ProxmoxURLRaw      *string `mapstructure:"proxmox_url" cty:"proxmox_url" hcl:"proxmox_url"`
	SkipCertValidation *bool   `mapstructure:"insecure_skip_tls_verify" cty:"insecure_skip_tls_verify" hcl:"insecure_skip_tls_verify"`
	Username           *string `mapstructure:"username" cty:"username" hcl:"username"`
	Password           *string `mapstructure:"password" cty:"password" hcl:"password"`
	Token              *string `mapstructure:"token" cty:"token" hcl:"token"`
	Node               *string `mapstructure:"node" cty:"node" hcl:"node"`
	Pool               *string `mapstructure:"pool" cty:"pool" hcl:"pool"`
	TaskTimeout        *string `mapstructure:"task_timeout" cty:"task_timeout" hcl:"task_timeout"`

	VMName *string `mapstructure:"vm_name" cty:"vm_name" hcl:"vm_name"`
	VMID   *int    `mapstructure:"vm_id" cty:"vm_id" hcl:"vm_id"`

	Ostemplate   *string `mapstructure:"ostemplate" cty:"ostemplate" hcl:"ostemplate"`
	RootFS       *string `mapstructure:"rootfs" cty:"rootfs" hcl:"rootfs"`
	Memory       *int    `mapstructure:"memory" cty:"memory" hcl:"memory"`
	Cores        *int    `mapstructure:"cores" cty:"cores" hcl:"cores"`
	Onboot       *bool   `mapstructure:"onboot" cty:"onboot" hcl:"onboot"`
	Start        *bool   `mapstructure:"start" cty:"start" hcl:"start"`
	Tags         *string `mapstructure:"tags" cty:"tags" hcl:"tags"`
	Nameserver   *string `mapstructure:"nameserver" cty:"nameserver" hcl:"nameserver"`
	SearchDomain *string `mapstructure:"searchdomain" cty:"searchdomain" hcl:"searchdomain"`
	Unprivileged *bool   `mapstructure:"unprivileged" cty:"unprivileged" hcl:"unprivileged"`

	NetworkAdapters []FlatNetworkAdapterConfig `mapstructure:"network_adapters" cty:"network_adapters" hcl:"network_adapters"`
	LXCConfig       map[string]interface{}     `mapstructure:"lxc_config" cty:"lxc_config" hcl:"lxc_config"`

	Type        *string `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	SSHHost     *string `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort     *int    `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername *string `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword *string `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHTimeout  *string `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	return map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},

		"proxmox_url":              &hcldec.AttrSpec{Name: "proxmox_url", Type: cty.String, Required: false},
		"insecure_skip_tls_verify": &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
		"username":                 &hcldec.AttrSpec{Name: "username", Type: cty.String, Required: false},
		"password":                 &hcldec.AttrSpec{Name: "password", Type: cty.String, Required: false},
		"token":                    &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"node":                     &hcldec.AttrSpec{Name: "node", Type: cty.String, Required: false},
		"pool":                     &hcldec.AttrSpec{Name: "pool", Type: cty.String, Required: false},
		"task_timeout":             &hcldec.AttrSpec{Name: "task_timeout", Type: cty.String, Required: false},
		"vm_name":                  &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"vm_id":                    &hcldec.AttrSpec{Name: "vm_id", Type: cty.Number, Required: false},
		"ostemplate":               &hcldec.AttrSpec{Name: "ostemplate", Type: cty.String, Required: false},
		"rootfs":                   &hcldec.AttrSpec{Name: "rootfs", Type: cty.String, Required: false},
		"memory":                   &hcldec.AttrSpec{Name: "memory", Type: cty.Number, Required: false},
		"cores":                    &hcldec.AttrSpec{Name: "cores", Type: cty.Number, Required: false},
		"onboot":                   &hcldec.AttrSpec{Name: "onboot", Type: cty.Bool, Required: false},
		"start":                    &hcldec.AttrSpec{Name: "start", Type: cty.Bool, Required: false},
		"tags":                     &hcldec.AttrSpec{Name: "tags", Type: cty.String, Required: false},
		"nameserver":               &hcldec.AttrSpec{Name: "nameserver", Type: cty.String, Required: false},
		"searchdomain":             &hcldec.AttrSpec{Name: "searchdomain", Type: cty.String, Required: false},
		"unprivileged":             &hcldec.AttrSpec{Name: "unprivileged", Type: cty.Bool, Required: false},
		"network_adapters":         &hcldec.BlockListSpec{TypeName: "network_adapters", Nested: hcldec.ObjectSpec((*FlatNetworkAdapterConfig)(nil).HCL2Spec())},
		"lxc_config":               &hcldec.AttrSpec{Name: "lxc_config", Type: cty.Map(cty.DynamicPseudoType), Required: false},
		"communicator":             &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"ssh_host":                 &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                 &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":             &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":             &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_timeout":              &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
	}
}

// FlatNetworkAdapterConfig is an auto-generated flat version of NetworkAdapterConfig.
type FlatNetworkAdapterConfig struct {
	Name        *string `mapstructure:"name" cty:"name" hcl:"name"`
	Bridge      *string `mapstructure:"bridge" cty:"bridge" hcl:"bridge"`
	Firewall    *bool   `mapstructure:"firewall" cty:"firewall" hcl:"firewall"`
	Gateway     *string `mapstructure:"gateway" cty:"gateway" hcl:"gateway"`
	GatewayIPv6 *string `mapstructure:"gateway_ipv6" cty:"gateway_ipv6" hcl:"gateway_ipv6"`
	IP          *string `mapstructure:"ip" cty:"ip" hcl:"ip"`
	IPv6        *string `mapstructure:"ipv6" cty:"ipv6" hcl:"ipv6"`
	MACAddress  *string `mapstructure:"mac_address" cty:"mac_address" hcl:"mac_address"`
	MTU         *int    `mapstructure:"mtu" cty:"mtu" hcl:"mtu"`
	Rate        *string `mapstructure:"rate" cty:"rate" hcl:"rate"`
	VLANTag     *string `mapstructure:"vlan_tag" cty:"vlan_tag" hcl:"vlan_tag"`
	Type        *string `mapstructure:"type" cty:"type" hcl:"type"`
}

// FlatMapstructure returns a new FlatNetworkAdapterConfig.
func (*NetworkAdapterConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkAdapterConfig)
}

// HCL2Spec returns the hcl spec of a NetworkAdapterConfig.
func (*FlatNetworkAdapterConfig) HCL2Spec() map[string]hcldec.Spec {
	return map[string]hcldec.Spec{
		"name":         &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"bridge":       &hcldec.AttrSpec{Name: "bridge", Type: cty.String, Required: false},
		"firewall":     &hcldec.AttrSpec{Name: "firewall", Type: cty.Bool, Required: false},
		"gateway":      &hcldec.AttrSpec{Name: "gateway", Type: cty.String, Required: false},
		"gateway_ipv6": &hcldec.AttrSpec{Name: "gateway_ipv6", Type: cty.String, Required: false},
		"ip":           &hcldec.AttrSpec{Name: "ip", Type: cty.String, Required: false},
		"ipv6":         &hcldec.AttrSpec{Name: "ipv6", Type: cty.String, Required: false},
		"mac_address":  &hcldec.AttrSpec{Name: "mac_address", Type: cty.String, Required: false},
		"mtu":          &hcldec.AttrSpec{Name: "mtu", Type: cty.Number, Required: false},
		"rate":         &hcldec.AttrSpec{Name: "rate", Type: cty.String, Required: false},
		"vlan_tag":     &hcldec.AttrSpec{Name: "vlan_tag", Type: cty.String, Required: false},
		"type":         &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
	}
}
